name: workout-tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.8.1
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cyrus-sasl=2.1.27
  - django=5.1.7
  - django-environ=0.12.0
  - djangorestframework=3.15.2
  - icu=75.1
  - krb5=1.21.3
  - libffi=3.4.2
  - libpq=17.4
  - openssl=3.4.1
  - pip=25.0.1
  - psycopg2=2.9.9
  - python=3.13
  - python-dotenv=1.0.1
  - sqlparse=0.5.3
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2025a
  - pip:
      - python-dotenv
